// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pokemon.Domain.Models
{
    public partial class PokemonMove
    {
        public int PokemonId { get; set; }
        public int MoveId { get; set; }
        public int Level { get; set; }

        public virtual Move Move { get; set; }
        public virtual Pokemon Pokemon { get; set; }
    }
}